[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "seri-ssh"
version = "0.1.0"
description = "SSH to PTY/serial bridge for WSL/Linux"
authors = [ {name = "", email = ""} ]
dependencies = [
    "asyncssh>=2.13.0",
]
